#!/bin/bash

. /opt/helpers

# exit, if no service requires local MySQL
{  [ "${ICINGA2_IDO_MYSQL_HOST}"         == "localhost" ] \
|| [ "${ICINGAWEB2_MYSQL_HOST}"          == "localhost" ] \
|| [ "${ICINGAWEB2_DIRECTOR_MYSQL_HOST}" == "localhost" ]
} || exit 0

chown -R mysql:mysql /var/lib/mysql
chmod +x /var/ /var/lib/ /var/lib/mysql/

if [ ! "$(ls -A /var/lib/mysql)" ]; then
	echo "=>MySQL datadir is empty...initializing"
	/usr/bin/mysql_install_db --user=mysql --basedir=/usr --datadir=/var/lib/mysql
fi

service mariadb start
mysql_wait localhost 3306
